#include "audio/effects/distortion/distortion.h"
#include "audio/effects/core/effect_factory.h"

namespace Amplitron {

static EffectRegistrar<Distortion> reg("Distortion");

Distortion::Distortion() {
    params_ = {
        {"Drive",  2.0f,  1.0f, 20.0f,  2.0f, "x", "Amount of input gain slamming into the hard clippers. Creates aggressive, dense harmonic distortion."},
        {"Tone",   0.6f,  0.0f,  1.0f,  0.6f, "", "Low-pass filter cutoff to tame the fizzy high-end generated by hard clipping."},
        {"Level",  0.5f,  0.0f,  1.0f,  0.5f, "", "Master output volume of the pedal. Useful to match volume with the pedal bypassed."},
    };
    drive_smoothed_ = params_[0].value;
    tone_smoothed_  = params_[1].value;
    level_smoothed_ = params_[2].value;
}

void Distortion::process(float* buffer, int num_samples) {
    if (!enabled_) return;

    const float mix = mix_.load(std::memory_order_relaxed);

    // One-pole smoothing: advance states toward raw param targets each block
    const float alpha = 1.0f - std::exp(-1.0f / (sample_rate_ * 0.010f)); // 10 ms
    drive_smoothed_ += alpha * (params_[0].value - drive_smoothed_);
    tone_smoothed_  += alpha * (params_[1].value - tone_smoothed_);
    level_smoothed_ += alpha * (params_[2].value - level_smoothed_);

    float drive = drive_smoothed_;
    float tone = tone_smoothed_;
    float level = level_smoothed_;

    // Tone control: simple one-pole LP filter coefficient
    float lp_coeff = 0.1f + tone * 0.8f;

    for (int i = 0; i < num_samples; ++i) {
        float dry = buffer[i];

        // Apply drive gain
        float x = buffer[i] * drive;

        // Soft path (tube-like via tanh + soft clip)
        float x_soft = soft_clip(fast_tanh(x) * 1.5f);

        // Hard path (hard clip at unity)
        float x_hard = hard_clip(x, 1.0f);

        // Blend: more drive → more hard clipping
        float hard_amount = (drive - params_[0].min_val) / (params_[0].max_val - params_[0].min_val);
        x = x_soft * (1.0f - hard_amount) + x_hard * hard_amount;

        // Tone filter (one-pole LP)
        x = tone_lp_.lp(x, lp_coeff);

        // Output level
        x *= level;

        // Wet/dry mix
        buffer[i] = dry * (1.0f - mix) + x * mix;
    }
}

void Distortion::reset() {
    tone_lp_.reset();
}

} // namespace Amplitron
