name: Clang-Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  formatting-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "18"
          check-path: "."
          fallback-style: "Google"
